#
# Adminer service for localhost
#
# Usage:
# docker compose -f .\infrastructure_localhost\adminer-docker-compose.yml --env-file .\config\.env.localhost up -d
#
services:
  
  adminer:
    image: adminer:5.3.0
    container_name: ${Environment}_adminer
    restart: always

    environment: 
      ADMINER_DEFAULT_SERVER: ${MYSQL_SERVER}:${MYSQL_PORT}
    ports:
      - "${ADMINER_PORT}:8080"

