#
# Template to create the database
#
services:
  production_database:
    image: mariadb:10.9
    container_name: production_database
    user: root
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    volumes:
      - production-database-volume:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

volumes:
  # docker volume create production-database-volume
  production-database-volume:
    external: true