#
# Adminer service for production
#
# Usage:
# docker compose -f .\infrastructure\adminer-docker-compose.yml --env-file .\config\.env.production up 
#
services:
  
  production-db-admin:
    image: adminer:5.3.0
    restart: always

    environment: 
      ADMINER_DEFAULT_SERVER: ${DB_HOST}:${DB_PORT}
    ports:
      - "${DB_ADMIN_PORT}:8080"

