#
# Template to create the database
#
# Usage:
# sudo docker compose -f ./infrastructure_production/database-docker-compose.yml --env-file ./config/.env.production up -d
#
services:
  database:
    image: mariadb:10.9
    container_name: ${Environment}_database
    user: root
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    volumes:
      - production-database-volume:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  # sudo docker volume rm production-database-volume
  # sudo docker volume create production-database-volume
  production-database-volume:
    external: true