#
# Deploy workflow for Database
#

name: Database - Deploy

defaults:
  run:
    working-directory: .
    
on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  staging:
    if: github.event.inputs.environment == 'staging'
    name: Deploy to Staging
    uses: ./.github/workflows/infrastructure-deploy-database.yml
    with:
      environment: staging
      project_name: database
    secrets: inherit

  production:
    if: github.event.inputs.environment == 'production'
    name: Deploy to Production
    uses: ./.github/workflows/infrastructure-deploy-database.yml
    with:
      environment: production
      project_name: database
    secrets: inherit

