#
# Build Deploy file for Docker container
# Change the variables in this section to match your project
#

name: Database - Deploy

defaults:
  run:
    working-directory: .
    
#
# Everything below this is template code
#

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  staging:
    if: github.event.inputs.environment == 'staging'
    name: Deploy to Staging
    uses: ./.github/workflows/infrastructure-deploy-step.yml
    with:
      environment: staging
      project_name: database
    secrets: inherit

  production:
    if: github.event.inputs.environment == 'production'
    name: Deploy to Production
    uses: ./.github/workflows/infrastructure-deploy-step.yml
    with:
      environment: production
      project_name: database
    secrets: inherit

